language: node_js
node_js:
- '4'
- 'stable'

after_script:
  - npm run test-cov
  - codecov -t 8df441bb-6a73-438b-9e3e-ffd2989b8664

sudo: false

codecov:
  token: 8df441bb-6a73-438b-9e3e-ffd2989b8664
